banner:
  location: boot.txt
server:
  port: 1111
spring:
  ds_sqlite:
    #url: jdbc:sqlite:timeDB.sqlite
    url: jdbc:sqlite:/Users/cgp/worksapcemoko/cgpfin/src/main/resources/timeDB.sqlite
    #url: jdbc:sqlite:C:/mydata/timeDB.sqlite
    driverClassName: org.sqlite.JDBC
logging:
  level:
    org:
      springframework: debug
    cc:
      cgp: debug
config:
  test:
    value1: sdfsffs