banner:
  location: boot.txt
server:
  port: 1111
spring:
  ds_sqlite:
    #url: jdbc:sqlite:/Users/cgp/Downloads/timeDB.sqlite
    url: jdbc:sqlite:C:/mydata/timeDB.sqlite
    driverClassName: org.sqlite.JDBC
logging:
  level:
    org:
      springframework: trace
config:
  test:
    value1: sdfsffs